Create sign up view, besides of generic files such as forms.py, base.…
codenation-dev/squad-6-ad-python-women-magalu-1 pull request #10
Opened 2019-10-30 04:36 UTC by tamesps

- [x] Sign Up View 
- [x] Form
- [x] Url
- [x] Template 
- [x] Migrations

2019-11-01 02:17 UTC, tamiryspino requested changes

2019-11-01 02:17 UTC, tamiryspino commented on central-erros/errorcenter/api/views.py
> +from errorcenter.forms import SignUpForm
Colocar os imports no topo do arquivo

2019-11-01 02:17 UTC, tamiryspino commented on central-erros/errorcenter/errorcenter/urls.py
> +    path('api/', include('api.urls'))
Pode apagar a linha comentada. Não sei a diferença dela para apenas o include.

2019-11-01 02:35 UTC, tamiryspino approved these changes

2019-11-02 02:22 UTC, ThaysPrado approved these changes

2019-11-02 02:22 UTC, merged