Level tamires
codenation-dev/squad-6-ad-python-women-magalu-1 pull request #6
Opened 2019-10-22 03:32 UTC by tamesps

Level:
- [ x] Models
- [ x] Serializers
- [ x] Urls
- [ x] Views
- [ x] Migrations

2019-10-23 01:23 UTC, tamiryspino requested changes

2019-10-23 01:23 UTC, tamiryspino commented on central-erros/errorcenter/api/urls.py
> +router.register(r'levels', views.OriginApiViewSet)
@tamesps `router.register(r'levels', views.OriginApiViewSet)` deveria ser `router.register(r'levels', views.LevelApiViewSet)`

2019-10-23 23:35 UTC, tamiryspino approved these changes

2019-10-25 03:08 UTC, ThaysPrado approved these changes

2019-10-25 23:06 UTC, merged